In [29]:
import pyarrow
import pandas as pd
import numpy as np
import pyodbc
from flask import Flask, render_template

In [2]:
customers = pd.read_csv('customers.csv')
customers

   customer_id first_name last_name        city  age            email
0            1      Ahmed    Hassan       Cairo   25  ahmed@email.com
1            2       Sara       Ali        Giza   31   sara@email.com
2            3       Omar   Mohamed       cairo   17   omar@email.com
3            4       Mona   Ibrahim  Alexandria   28              NaN
4            5      Ahmed    Hassan       Cairo   25  ahmed@email.com

In [3]:
customers.drop(4,inplace=True)
customers

   customer_id first_name last_name        city  age            email
0            1      Ahmed    Hassan       Cairo   25  ahmed@email.com
1            2       Sara       Ali        Giza   31   sara@email.com
2            3       Omar   Mohamed       cairo   17   omar@email.com
3            4       Mona   Ibrahim  Alexandria   28              NaN

In [4]:
customers['city'] = customers['city'].str.lower()
customers

   customer_id first_name last_name        city  age            email
0            1      Ahmed    Hassan       cairo   25  ahmed@email.com
1            2       Sara       Ali        giza   31   sara@email.com
2            3       Omar   Mohamed       cairo   17   omar@email.com
3            4       Mona   Ibrahim  alexandria   28              NaN

In [5]:
customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customer_id  4 non-null      int64
 1   first_name   4 non-null      str
 2   last_name    4 non-null      str
 3   city         4 non-null      str
 4   age          4 non-null      int64
 5   email        3 non-null      str
dtypes: int64(2), str(4)
memory usage: 435.0 bytes

In [6]:
customers.fillna('none', inplace=True)
customers

   customer_id first_name last_name        city  age            email
0            1      Ahmed    Hassan       cairo   25  ahmed@email.com
1            2       Sara       Ali        giza   31   sara@email.com
2            3       Omar   Mohamed       cairo   17   omar@email.com
3            4       Mona   Ibrahim  alexandria   28             none

In [7]:
customers['fullname'] = customers['first_name'] + ' ' + customers['last_name']
customers

,customer_id,first_name,last_name,city,age,email,fullname
0,1,Ahmed,Hassan,cairo,25,ahmed@email.com,Ahmed Hassan
1,2,Sara,Ali,giza,31,sara@email.com,Sara Ali
2,3,Omar,Mohamed,cairo,17,omar@email.com,Omar Mohamed
3,4,Mona,Ibrahim,alexandria,28,none,Mona Ibrahim

In [8]:
orders = pd.read_parquet('orders.parquet', engine ='pyarrow')
orders

    order_id  customer_id  product_id  quantity order_date
0       1001            1         101         2 2026-09-01
1       1002            2         102         1 2026-09-01
2       1003            3         103         3 2026-09-02
3       1004            4         101         1 2026-09-02
4       1005            1         104         2 2026-09-03
5       1006            5         102         1 2026-09-03
6       1007            2         105         4 2026-09-04
7       1008            3         101         1 2026-09-04
8       1009            4         103         2 2026-09-05
9       1010            1         104         1 2026-09-05
10      1003            3         103         3 2026-09-02

In [9]:
orders.drop_duplicates(inplace = True)
orders

   order_id  customer_id  product_id  quantity order_date
0      1001            1         101         2 2026-09-01
1      1002            2         102         1 2026-09-01
2      1003            3         103         3 2026-09-02
3      1004            4         101         1 2026-09-02
4      1005            1         104         2 2026-09-03
5      1006            5         102         1 2026-09-03
6      1007            2         105         4 2026-09-04
7      1008            3         101         1 2026-09-04
8      1009            4         103         2 2026-09-05
9      1010            1         104         1 2026-09-05

In [10]:
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   order_id     10 non-null     int64
 1   customer_id  10 non-null     int64
 2   product_id   10 non-null     int64
 3   quantity     10 non-null     int64
 4   order_date   10 non-null     datetime64[us]
dtypes: datetime64[us](1), int64(4)
memory usage: 532.0 bytes

In [11]:
orders.loc[5, 'customer_id'] = 1
orders

   order_id  customer_id  product_id  quantity order_date
0      1001            1         101         2 2026-09-01
1      1002            2         102         1 2026-09-01
2      1003            3         103         3 2026-09-02
3      1004            4         101         1 2026-09-02
4      1005            1         104         2 2026-09-03
5      1006            1         102         1 2026-09-03
6      1007            2         105         4 2026-09-04
7      1008            3         101         1 2026-09-04
8      1009            4         103         2 2026-09-05
9      1010            1         104         1 2026-09-05

In [12]:
url = 'https://raw.githubusercontent.com/MohammedHameds/test1455/refs/heads/main/products.csv'
products = pd.read_csv(url)
products

   product_id product_name     category  unit_price
0         101       Laptop  Electronics       25000
1         102        Mouse  Accessories         500
2         103     Keyboard  Accessories        1200
3         104      Monitor  Electronics        7000
4         105   Headphones  Accessories        2500
5         106       Webcam  Accessories        1800

In [13]:
products.duplicated().sum()

np.int64(0)

In [14]:
products['category'] = products['category'].str.strip()
products['product_name'] = products['product_name'].str.strip()
products

   product_id product_name     category  unit_price
0         101       Laptop  Electronics       25000
1         102        Mouse  Accessories         500
2         103     Keyboard  Accessories        1200
3         104      Monitor  Electronics        7000
4         105   Headphones  Accessories        2500
5         106       Webcam  Accessories        1800

In [15]:
products.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    6 non-null      int64
 1   product_name  6 non-null      str
 2   category      6 non-null      str
 3   unit_price    6 non-null      int64
dtypes: int64(2), str(2)
memory usage: 434.0 bytes

In [16]:
sales = orders.merge(customers, how='inner', on='customer_id').merge(products, how='inner', on='product_id')
sales

,order_id,customer_id,product_id,quantity,order_date,first_name,last_name,city,age,email,fullname,product_name,category,unit_price
0,1001,1,101,2,2026-09-01,Ahmed,Hassan,cairo,25,ahmed@email.com,Ahmed Hassan,Laptop,Electronics,25000
1,1002,2,102,1,2026-09-01,Sara,Ali,giza,31,sara@email.com,Sara Ali,Mouse,Accessories,500
2,1003,3,103,3,2026-09-02,Omar,Mohamed,cairo,17,omar@email.com,Omar Mohamed,Keyboard,Accessories,1200
3,1004,4,101,1,2026-09-02,Mona,Ibrahim,alexandria,28,none,Mona Ibrahim,Laptop,Electronics,25000
4,1005,1,104,2,2026-09-03,Ahmed,Hassan,cairo,25,ahmed@email.com,Ahmed Hassan,Monitor,Electronics,7000
5,1006,1,102,1,2026-09-03,Ahmed,Hassan,cairo,25,ahmed@email.com,Ahmed Hassan,Mouse,Accessories,500
6,1007,2,105,4,2026-09-04,Sara,Ali,giza,31,sara@email.com,Sara Ali,Headphones,Accessories,2500
7,1008,3,101,1,2026-09-04,Omar,Mohamed,cairo,17,omar@email.com,Omar Mohamed,Laptop,Electronics,25000
8,1009,4,103,2,2026-09-05,Mona,Ibrahim,alexandria,28,none,Mona Ibrahim,Keyboard,Accessories,1200
9,1010,1,104,1,2026-09-05,Ahmed,Hassan,cairo,25,ahmed@email.com,Ahmed Hassan,Monitor,Electronics,7000

In [17]:
sales["total_amount"] = sales["quantity"] * sales["unit_price"]
sales

,order_id,customer_id,product_id,quantity,order_date,first_name,last_name,city,age,email,fullname,product_name,category,unit_price,total_amount
0,1001,1,101,2,2026-09-01,Ahmed,Hassan,cairo,25,ahmed@email.com,Ahmed Hassan,Laptop,Electronics,25000,50000
1,1002,2,102,1,2026-09-01,Sara,Ali,giza,31,sara@email.com,Sara Ali,Mouse,Accessories,500,500
2,1003,3,103,3,2026-09-02,Omar,Mohamed,cairo,17,omar@email.com,Omar Mohamed,Keyboard,Accessories,1200,3600
3,1004,4,101,1,2026-09-02,Mona,Ibrahim,alexandria,28,none,Mona Ibrahim,Laptop,Electronics,25000,25000
4,1005,1,104,2,2026-09-03,Ahmed,Hassan,cairo,25,ahmed@email.com,Ahmed Hassan,Monitor,Electronics,7000,14000
5,1006,1,102,1,2026-09-03,Ahmed,Hassan,cairo,25,ahmed@email.com,Ahmed Hassan,Mouse,Accessories,500,500
6,1007,2,105,4,2026-09-04,Sara,Ali,giza,31,sara@email.com,Sara Ali,Headphones,Accessories,2500,10000
7,1008,3,101,1,2026-09-04,Omar,Mohamed,cairo,17,omar@email.com,Omar Mohamed,Laptop,Electronics,25000,25000
8,1009,4,103,2,2026-09-05,Mona,Ibrahim,alexandria,28,none,Mona Ibrahim,Keyboard,Accessories,1200,2400
9,1010,1,104,1,2026-09-05,Ahmed,Hassan,cairo,25,ahmed@email.com,Ahmed Hassan,Monitor,Electronics,7000,7000

In [18]:
sales = sales[['order_id','fullname','product_name','quantity','unit_price','total_amount']]
sales.rename(columns={'fullname' : 'customer', 'product_name' : 'product'}, inplace = True)
sales

   order_id      customer     product  quantity  unit_price  total_amount
0      1001  Ahmed Hassan      Laptop         2       25000         50000
1      1002      Sara Ali       Mouse         1         500           500
2      1003  Omar Mohamed    Keyboard         3        1200          3600
3      1004  Mona Ibrahim      Laptop         1       25000         25000
4      1005  Ahmed Hassan     Monitor         2        7000         14000
5      1006  Ahmed Hassan       Mouse         1         500           500
6      1007      Sara Ali  Headphones         4        2500         10000
7      1008  Omar Mohamed      Laptop         1       25000         25000
8      1009  Mona Ibrahim    Keyboard         2        1200          2400
9      1010  Ahmed Hassan     Monitor         1        7000          7000

In [31]:
conn = pyodbc.connect(
    "driver={ODBC Driver 17 for SQL Server};"
    "server=localhost\\SQLEXPRESS;"
    "database=master;"
    "trusted_connection=yes;"
)

cursor = conn.cursor()

In [22]:
cursor.execute('create table sales (id int primary key , customer varchar(50) , product varchar(50) , quantity int, price int, total_amount int)')
cursor.commit()

In [24]:
rows = list(sales.itertuples(index=False, name=None))
rows

[(1001, 'Ahmed Hassan', 'Laptop', 2, 25000, 50000),
 (1002, 'Sara Ali', 'Mouse', 1, 500, 500),
 (1003, 'Omar Mohamed', 'Keyboard', 3, 1200, 3600),
 (1004, 'Mona Ibrahim', 'Laptop', 1, 25000, 25000),
 (1005, 'Ahmed Hassan', 'Monitor', 2, 7000, 14000),
 (1006, 'Ahmed Hassan', 'Mouse', 1, 500, 500),
 (1007, 'Sara Ali', 'Headphones', 4, 2500, 10000),
 (1008, 'Omar Mohamed', 'Laptop', 1, 25000, 25000),
 (1009, 'Mona Ibrahim', 'Keyboard', 2, 1200, 2400),
 (1010, 'Ahmed Hassan', 'Monitor', 1, 7000, 7000)]

In [25]:
cursor.executemany('insert into sales values (?,?,?,?,?,?)', rows)
cursor.commit()

In [34]:
app = Flask(__name__)

@app.route('/')
def home():
    df = pd.read_sql_query('select * from sales', conn)
    return render_template('home.html', table = df.to_html())


if __name__ == '__main__':
    app.run(port = 5000)

 * Serving Flask app '__main__'
 * Debug mode: off

WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
Press CTRL+C to quit
C:\Users\Fares\AppData\Local\Temp\ipykernel_21304\3631678958.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query('select * from sales', conn)
127.0.0.1 - - [17/Sep/2026 18:56:25] "GET / HTTP/1.1" 200 -
C:\Users\Fares\AppData\Local\Temp\ipykernel_21304\3631678958.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query('select * from sales', conn)
127.0.0.1 - - [17/Sep/2026 18:56:31] "GET / HTTP/1.1" 200 -

In [35]:
conn.close()